name: easybreezy
description: An app that helps homeowners reduce air conditioning use by notifying them when it's a good time to open their windows.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  provider: ^6.0.5
  http: ^1.4.0
  shared_preferences: ^2.1.1
  flutter_local_notifications: ^19.3.0
  geolocator: ^9.0.2
  intl: ^0.20.2
  flutter_compass: ^0.8.1
  permission_handler: ^12.0.0+1
  flutter_svg: ^2.0.5
  geocoding: ^2.1.0
  flutter_neumorphic: ^3.2.0
  fl_chart: ^0.68.0
  url_launcher: ^6.3.2
  firebase_core: ^3.15.2
  firebase_messaging: ^15.2.10
  card_swiper: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/backgrounds/
    - assets/images/window-installers-placehold.jpg
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500