name: easybreezy
description: An app that helps homeowners reduce air conditioning use by notifying them when it's a good time to open their windows.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  provider: ^6.0.5
  http: ^1.4.0
  shared_preferences: ^2.1.1
  flutter_local_notifications: ^19.3.0
  geolocator: ^14.0.1
  intl: ^0.20.2
  flutter_compass: ^0.8.1
  permission_handler: ^12.0.0+1
  flutter_svg: ^2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500